### ISSUE TITLE
Images not showing on Chrome or Safari

### ISSUE THREAD

**Issue by jcbbuller** [robin-dela/hover-effect#12]
Hello,

I would really love to use this feature on my portfolio site but when I download the files and view the examples on Chrome and Safari the images do not show. They show in Firefox though... The CodePen example you posted doesn't work on Chrome either.

**Comment by jcbbuller** [comment]
I found a solution by pulling from another person's project. This should be a working example that people having this issue can implement into their site - https://github.com/jcbbuller/WebGL-hover-distortion

**Comment by robin-dela** [comment]
Hey,

I assume the images are not showing because you're viewing the example locally and not via a server (see [this issue](https://github.com/robin-dela/hover-effect/issues/11)).

The codepen project is not showing for a different reason, the library is linked to it via rawgit, which is not working anymore
